---
- include_tasks: "_download_enmasse_artifact.yml"

- include_tasks: "_install_enmasse_from_artifact.yml"

- name: Delete enmasse restapi route
  shell:  oc delete route/restapi -n {{ enmasse_namespace }}
  register: restapi_delete_cmd
  failed_when: restapi_delete_cmd.stderr != '' and 'not found' not in restapi_delete_cmd.stderr

- include_tasks: ./check_readiness.yml
